# class_mapping.py
# Berisi kamus (dictionary) nama 43 kelas rambu lalu lintas dari dataset GTSRB.
# Dipisah dari app.py supaya kode utama tidak terlalu panjang, tinggal di-import.
#
# Setiap kelas punya:
# - "name_id"    : nama rambu dalam Bahasa Indonesia (ditampilkan di web)
# - "name_en"    : nama asli dari dataset GTSRB (untuk referensi)
# - "category"   : kategori rambu, dipakai untuk menentukan warna kartu hasil
#                  "larangan" / "bahaya" -> ditampilkan warna merah
#                  "wajib"               -> ditampilkan warna biru
# - "keterangan" : penjelasan singkat arti rambu, ditampilkan di halaman klasifikasi

CLASS_NAMES = {
    0:  {"name_id": "Batas Kecepatan 20 km/jam", "name_en": "Speed limit (20km/h)", "category": "larangan",
         "keterangan": "Kendaraan dilarang melaju lebih dari 20 km/jam pada ruas jalan ini."},
    1:  {"name_id": "Batas Kecepatan 30 km/jam", "name_en": "Speed limit (30km/h)", "category": "larangan",
         "keterangan": "Kendaraan dilarang melaju lebih dari 30 km/jam pada ruas jalan ini."},
    2:  {"name_id": "Batas Kecepatan 50 km/jam", "name_en": "Speed limit (50km/h)", "category": "larangan",
         "keterangan": "Kendaraan dilarang melaju lebih dari 50 km/jam pada ruas jalan ini."},
    3:  {"name_id": "Batas Kecepatan 60 km/jam", "name_en": "Speed limit (60km/h)", "category": "larangan",
         "keterangan": "Kendaraan dilarang melaju lebih dari 60 km/jam pada ruas jalan ini."},
    4:  {"name_id": "Batas Kecepatan 70 km/jam", "name_en": "Speed limit (70km/h)", "category": "larangan",
         "keterangan": "Kendaraan dilarang melaju lebih dari 70 km/jam pada ruas jalan ini."},
    5:  {"name_id": "Batas Kecepatan 80 km/jam", "name_en": "Speed limit (80km/h)", "category": "larangan",
         "keterangan": "Kendaraan dilarang melaju lebih dari 80 km/jam pada ruas jalan ini."},
    6:  {"name_id": "Akhir Batas Kecepatan 80 km/jam", "name_en": "End of speed limit (80km/h)", "category": "wajib",
         "keterangan": "Batas kecepatan 80 km/jam yang berlaku sebelumnya telah berakhir."},
    7:  {"name_id": "Batas Kecepatan 100 km/jam", "name_en": "Speed limit (100km/h)", "category": "larangan",
         "keterangan": "Kendaraan dilarang melaju lebih dari 100 km/jam pada ruas jalan ini."},
    8:  {"name_id": "Batas Kecepatan 120 km/jam", "name_en": "Speed limit (120km/h)", "category": "larangan",
         "keterangan": "Kendaraan dilarang melaju lebih dari 120 km/jam pada ruas jalan ini."},
    9:  {"name_id": "Dilarang Mendahului", "name_en": "No passing", "category": "larangan",
         "keterangan": "Kendaraan dilarang menyalip kendaraan lain pada ruas jalan ini."},
    10: {"name_id": "Dilarang Mendahului (Kendaraan di atas 3.5 Ton)", "name_en": "No passing for vehicles over 3.5 metric tons", "category": "larangan",
         "keterangan": "Kendaraan berat di atas 3.5 ton dilarang menyalip kendaraan lain."},
    11: {"name_id": "Hak Utama di Persimpangan Berikutnya", "name_en": "Right-of-way at the next intersection", "category": "wajib",
         "keterangan": "Pengendara memiliki hak utama jalan pada persimpangan di depan."},
    12: {"name_id": "Jalan Prioritas", "name_en": "Priority road", "category": "wajib",
         "keterangan": "Menandakan pengendara sedang berada di jalan dengan prioritas utama."},
    13: {"name_id": "Beri Jalan (Yield)", "name_en": "Yield", "category": "larangan",
         "keterangan": "Pengendara wajib memberi jalan kepada kendaraan dari arah lain."},
    14: {"name_id": "Berhenti (Stop)", "name_en": "Stop", "category": "larangan",
         "keterangan": "Kendaraan wajib berhenti total sebelum melanjutkan perjalanan."},
    15: {"name_id": "Dilarang Dilalui Segala Kendaraan", "name_en": "No vehicles", "category": "larangan",
         "keterangan": "Semua jenis kendaraan dilarang melintas pada ruas jalan ini."},
    16: {"name_id": "Dilarang Dilalui Kendaraan di atas 3.5 Ton", "name_en": "Vehicles over 3.5 metric tons prohibited", "category": "larangan",
         "keterangan": "Kendaraan dengan berat di atas 3.5 ton dilarang melintas."},
    17: {"name_id": "Dilarang Masuk", "name_en": "No entry", "category": "larangan",
         "keterangan": "Kendaraan dilarang masuk ke jalan tersebut dari arah manapun."},
    18: {"name_id": "Peringatan Umum / Hati-hati", "name_en": "General caution", "category": "bahaya",
         "keterangan": "Menandakan adanya potensi bahaya umum di depan, pengendara harus lebih waspada."},
    19: {"name_id": "Tikungan Tajam ke Kiri", "name_en": "Dangerous curve to the left", "category": "bahaya",
         "keterangan": "Jalan di depan berbelok tajam ke arah kiri."},
    20: {"name_id": "Tikungan Tajam ke Kanan", "name_en": "Dangerous curve to the right", "category": "bahaya",
         "keterangan": "Jalan di depan berbelok tajam ke arah kanan."},
    21: {"name_id": "Tikungan Ganda", "name_en": "Double curve", "category": "bahaya",
         "keterangan": "Jalan di depan memiliki dua tikungan berturut-turut."},
    22: {"name_id": "Jalan Bergelombang", "name_en": "Bumpy road", "category": "bahaya",
         "keterangan": "Permukaan jalan di depan tidak rata, pengendara harus mengurangi kecepatan."},
    23: {"name_id": "Jalan Licin", "name_en": "Slippery road", "category": "bahaya",
         "keterangan": "Permukaan jalan berpotensi licin, terutama saat basah."},
    24: {"name_id": "Jalan Menyempit di Sisi Kanan", "name_en": "Road narrows on the right", "category": "bahaya",
         "keterangan": "Lebar jalan di depan menyempit dari sisi kanan."},
    25: {"name_id": "Ada Pekerjaan Jalan", "name_en": "Road work", "category": "bahaya",
         "keterangan": "Terdapat kegiatan perbaikan atau pembangunan jalan di depan."},
    26: {"name_id": "Lampu Lalu Lintas di Depan", "name_en": "Traffic signals", "category": "bahaya",
         "keterangan": "Terdapat lampu lalu lintas (traffic light) di ruas jalan berikutnya."},
    27: {"name_id": "Rawan Penyeberang Jalan Kaki", "name_en": "Pedestrians", "category": "bahaya",
         "keterangan": "Area rawan dilintasi pejalan kaki, pengendara harus lebih berhati-hati."},
    28: {"name_id": "Rawan Anak-anak Menyeberang", "name_en": "Children crossing", "category": "bahaya",
         "keterangan": "Area rawan anak-anak menyeberang, biasanya dekat sekolah."},
    29: {"name_id": "Rawan Sepeda Melintas", "name_en": "Bicycles crossing", "category": "bahaya",
         "keterangan": "Area rawan dilintasi pesepeda."},
    30: {"name_id": "Awas Es/Salju", "name_en": "Beware of ice/snow", "category": "bahaya",
         "keterangan": "Jalan berpotensi licin karena es atau salju."},
    31: {"name_id": "Rawan Hewan Liar Menyeberang", "name_en": "Wild animals crossing", "category": "bahaya",
         "keterangan": "Area rawan dilintasi hewan liar."},
    32: {"name_id": "Akhir Seluruh Batas Kecepatan dan Larangan Mendahului", "name_en": "End of all speed and passing limits", "category": "wajib",
         "keterangan": "Seluruh pembatasan kecepatan dan larangan menyalip sebelumnya telah berakhir."},
    33: {"name_id": "Wajib Belok Kanan", "name_en": "Turn right ahead", "category": "wajib",
         "keterangan": "Kendaraan wajib berbelok ke arah kanan di depan."},
    34: {"name_id": "Wajib Belok Kiri", "name_en": "Turn left ahead", "category": "wajib",
         "keterangan": "Kendaraan wajib berbelok ke arah kiri di depan."},
    35: {"name_id": "Wajib Lurus", "name_en": "Ahead only", "category": "wajib",
         "keterangan": "Kendaraan hanya boleh melaju lurus."},
    36: {"name_id": "Wajib Lurus atau Belok Kanan", "name_en": "Go straight or right", "category": "wajib",
         "keterangan": "Kendaraan boleh melaju lurus atau berbelok ke kanan."},
    37: {"name_id": "Wajib Lurus atau Belok Kiri", "name_en": "Go straight or left", "category": "wajib",
         "keterangan": "Kendaraan boleh melaju lurus atau berbelok ke kiri."},
    38: {"name_id": "Wajib Mengambil Jalur Kanan", "name_en": "Keep right", "category": "wajib",
         "keterangan": "Kendaraan wajib mengambil jalur di sisi kanan."},
    39: {"name_id": "Wajib Mengambil Jalur Kiri", "name_en": "Keep left", "category": "wajib",
         "keterangan": "Kendaraan wajib mengambil jalur di sisi kiri."},
    40: {"name_id": "Wajib Mengikuti Bundaran", "name_en": "Roundabout mandatory", "category": "wajib",
         "keterangan": "Kendaraan wajib mengikuti arah bundaran (roundabout)."},
    41: {"name_id": "Akhir Larangan Mendahului", "name_en": "End of no passing", "category": "wajib",
         "keterangan": "Larangan menyalip sebelumnya telah berakhir."},
    42: {"name_id": "Akhir Larangan Mendahului (Kendaraan di atas 3.5 Ton)", "name_en": "End of no passing by vehicles over 3.5 metric tons", "category": "wajib",
         "keterangan": "Larangan menyalip untuk kendaraan berat di atas 3.5 ton telah berakhir."},
}

TOTAL_CLASS = len(CLASS_NAMES)  # 43